language: node_js
node_js:
  - 12

services:
- postgresql
env: 
- DATABASE_URL='postgresql://postgres:moddy123@localhost:5432/greetingWeb'

before_script:
- psql -c 'create database greetingWeb;' -U postgres
- psql -U postgres -d greetingWeb -a -f table.sql 